# Generated by Django 4.0.4 on 2022-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.IntegerField()),
                ('total_no', models.IntegerField()),
                ('meandiff', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medianramp', models.DecimalField(decimal_places=1, max_digits=8)),
                ('sddiff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('normality', models.CharField(max_length=6)),
                ('scf90', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scf95', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scf99', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
