# Generated by Django 4.0.4 on 2022-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
